# -*- coding: utf-8 -*-
"""flower_recog.model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDI6GUv2PF21jiE9WyXUvADC0469oHbN
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator



#data preprocessing

#traning image processing

train_datagen = ImageDataGenerator(
                rescale=1./255,
                shear_range=0.2,
                zoom_range=0.2,
                horizontal_flip=True)
training_set = train_datagen.flow_from_directory(
               '/content/drive/MyDrive/flower_recognition..model/training_set',
               target_size=(64,64),
               batch_size=32,
               class_mode='categorical')

#test image processing

test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory('/content/drive/MyDrive/flower_recognition..model/test_set',
                         target_size=(64, 64),
                         batch_size=32,
                         class_mode='categorical')

#building model

cnn = tf.keras.models.Sequential()

#building convolution layer

cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu',input_shape=[64,64,3]))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu',input_shape=[64,64,3]))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

cnn.add(tf.keras.layers.Dropout(0.5))

cnn.add(tf.keras.layers.Flatten())

cnn.add(tf.keras.layers.Dense(units=128,activation='relu'))

cnn.add(tf.keras.layers.Dense(units=5,activation='softmax'))

cnn.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

cnn.fit(x=training_set, validation_data=test_set, epochs=30)

from google.colab import drive
drive.mount('/content/drive')

#preprocess new image

from keras.preprocessing import image
test_image = image.load_img('/content/drive/MyDrive/flower_recognition..model/prediction/dandalion.jpg',target_size=(64,64))
test_image = np.expand_dims(test_image,axis=0)
result = cnn.predict(test_image)

training_set.class_indices

print(result)

if result[0][0]==1:
    print('Daisy')
elif result[0][1]==1:
      print('dandeleion')
elif result[0][2]==1:
       print('roses')
elif result[0][3]==1:
        print('sunflower')
elif result[0][4]==1:
        print('tulip')